### ISSUE TITLE
关于ieskf更新代码中的疑问

### ISSUE THREAD

**Issue by SharkPeppero** [liangheming/FASTLIO2_ROS2#10]
！！！！！！！！！！！！【大佬，关于ieskf更新过程的疑惑，希望您可以帮我看一下】！！！！！！！！！！
！！！！！！！！！！！！【大佬，关于ieskf更新过程的疑惑，希望您可以帮我看一下】！！！！！！！！！！
！！！！！！！！！！！！【大佬，关于ieskf更新过程的疑惑，希望您可以帮我看一下】！！！！！！！！！！

![wenti](https://github.com/user-attachments/assets/244f5805-ed7f-49a5-b2dd-1ff07f001844)

在ieskf更新的过程中，我理解的是先利用激光雷达的点面残差观测组织了关于平移旋转的高斯牛顿 H * delta_x = -J * err；
但图片中红色部分，为什么可以利用 【误差量】【误差状态量的协方差】 又组织一次 高斯牛顿？这样写的依据是什么呀，已经困惑好久了，希望您可以指点一下 
    拜托了~~~~~

**Comment by SharkPeppero** [comment]
好的 谢谢~

**Comment by KJ-Falloutlast** [comment]
我理解的，这里的J相当于delta_p,delta_q, delta_bg的每一次迭代delta_x{i+1}对delta_x{i}的雅可比，然后不断用J.T * P * J来更新观测矩阵H，以及b。
![10e1bdb757e0a086f0e61d05fc7edf3](https://github.com/user-attachments/assets/5ed60970-45b8-420d-a0a9-9275fafcdfc3)
![a601dcca29947bcb718fb1f288b8453](https://github.com/user-attachments/assets/77976f42-d56e-44b2-95d7-5847dbfc3005)
