### ISSUE TITLE
hba 优化问题

### ISSUE THREAD

**Issue by Liansheng-Wang** [liangheming/FASTLIO2_ROS2#11]
我测试了你提供的数据集，hba 的优化过程似乎并没有改善最终的结果，至少不是很明显。你有遇到类似的情况吗？

**Comment by liangheming** [comment]
是的，如果优化前里程计本身就已经很好了的话，再进行优化不会有明显提升，相反还会使得结果更差，建议可以先加一些噪声，再进行优化。另外，因为这个repo的HBA，我是参考论文实现，没有做过全面对比，建议可以使用官方实现比对一下结果
