### ISSUE TITLE
我想请问一下，这个重定位是手动的吗

### ISSUE THREAD

**Issue by LL-LIVE** [liangheming/FASTLIO2_ROS2#2]
我只看到了手动的代码，没有看见有特征提取和匹配的代码

**Comment by liangheming** [comment]
这个重定位是基于ICP的方式，不是基于特征的方式，基于特征的请参考ScanContext或者STD

**Comment by LL-LIVE** [comment]
抱歉抱歉，我刚想回来评论，是我没看清楚，是的，基于icp。这一篇真的很厉害！！！

**Comment by liangheming** [comment]
好的，那我关issue了
