### ISSUE TITLE
local雷达坐标是不是写错了

### ISSUE THREAD

**Issue by LL-LIVE** [liangheming/FASTLIO2_ROS2#3]
![image](https://github.com/liangheming/FASTLIO2_ROS2/assets/175204804/183fb14a-3b27-4ce8-ab7c-0812dddc1f79)
这个local_frame是不是应该是body
![image](https://github.com/liangheming/FASTLIO2_ROS2/assets/175204804/b6d6498f-23a6-4f4a-b831-040514382525)

**Comment by liangheming** [comment]
应该是没错的，map_frame是地图的全局坐标系，local_frame是里程计的局部坐标系，body是运动体坐标系，tf_tree的结构应该是 map_frame->local_frame->body， 如果有GPS的话，还有会一个world_frame 世界坐标系。 map_frame->local_frame之间的修正就是靠的重定位，而local_frame->body_frame主要是lio里程计；

**Comment by LL-LIVE** [comment]
但是，不是要把话题body_cloud的点云往全局地图上面靠吗，改动的不应该是body_cloud的坐标系吗

**Comment by LL-LIVE** [comment]
我理解了，其实我们需要的是让之前的world_cloud和现在的map_cloud去匹配，是没有错的
