### ISSUE TITLE
请问数据集使用的是livox的哪一款激光雷达，mid360可以做吗？

### ISSUE THREAD

**Issue by frostdogstarscream** [liangheming/FASTLIO2_ROS2#7]

**Comment by liangheming** [comment]
用的就是livox mid360。

**Comment by frostdogstarscream** [comment]
&nbsp;好的，非常感谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liangheming/FASTLIO2_ROS2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月6日(星期二) 晚上11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liangheming/FASTLIO2_ROS2] 请问数据集使用的是livox的哪一款激光雷达，mid360可以做吗？ (Issue #7)





 
用的就是livox mid360。
