### ISSUE TITLE
请问该项目支持MID360倒置吗

### ISSUE THREAD

**Issue by HomeworldL** [liangheming/FASTLIO2_ROS2#9]
在[lio.yaml](https://github.com/liangheming/FASTLIO2_ROS2/blob/main/fastlio2/config/lio.yaml)配置文件中没有看到雷达坐标系的相关参数，请问默认是雷达正放吗？如果想要更改雷达的安装方向，请问可以从哪入手改呢？

**Comment by liangheming** [comment]
原理上支持任何放置方式，在IMU初始化阶段尽量静态初始化，有一个对齐重力的选项，开启重力对齐后，会直接估计出一个雷达放置朝向和重力朝向的相对旋转作为初始朝向，这样可以不用考虑实车上雷达的放置位置，如果你需要调整，建议在初始化的时候

**Comment by HomeworldL** [comment]
好的，谢谢，已经使用该库实现了正放/倒置/前置三种位置的建图和重定位。
